POST http://localhost:3333/palavras
Content-Type: application/json

{
    "id": 2,
    "palavra": "node"
}

###

GET http://localhost:3333/palavras?search=node

###

PUT http://localhost:3333/palavras/1
Content-Type: application/json

{
    "palavra": "c"
}

###

DELETE http://localhost:3333/palavras/1